modLoader="javafml"
loaderVersion="[40,41)"
license="GPLv3"

[[mods]]
modId="luremod"
version="1.0.1"
displayName="Attract to Fire Mod"
authors="Sylsatra"
description='''A mod to make mobs Fascinated with fire.'''

[[dependencies.fearofire]]
modId="forge"
mandatory=true
versionRange="[40,)" 
ordering="NONE"
side="BOTH"

[[dependencies.fearofire]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)" 
ordering="NONE"
side="BOTH"
